INSERT INTO `awolski`.`Genre` (`GenreName`) VALUES 
('Shooter'),
('Role-playing (RPG)'),
('Strategy'),
('Turn-based strategy (TBS)'),
('Tactical'),
('Fighting'),
('Adventure'),
('Real Time Strategy (RTS)'),
('Simulator'),
('Point-and-click'),
('unknown'),
('Hack and slash/Beat'),
('Puzzle'),
('Platform'),
('Racing'),
('Arcade'),
('Indie'),
('Sport'),
('Quiz/Trivia'),
('Pinball');
