INSERT INTO `awolski`.`Plateform` (`PlateformName`) VALUES 
('Microsoft Windows'),
('Xbox'),
('PlayStation 3'),
('PlayStation 4'),
('Xbox 360'),
('Xbox One'),
('Linux'),
('Mac'),
('PC DOS'),
('Nintendo DS'),
('Amiga'),
('PlayStation 2'),
('Game Boy Advance'),
('iOS'),
('Android'),
('PlayStation'),
('Apple II'),
('Atari ST/STE'),
('PlayStation Network'),
('Wii'),
('Sega Mega Drive/Genesis'),
('Super Nintendo Entertainment System (SNES)'),
('3DO Interactive Multiplayer'),
('Atari Jaguar'),
('Sega CD'),
('Amiga CD32'),
('FM Towns'),
('Xbox Live Arcade'),
('Wii U'),
('Nintendo GameCube'),
('Acorn Archimedes'),
('Sega Saturn'),
('PlayStation Portable'),
('Commodore C64/128'),
('PlayStation Vita'),
('Windows Phone'),
('Nintendo 64'),
('Game Boy Color'),
('Dreamcast'),
('Game Boy'),
('Sega Game Gear'),
('Amstrad CPC'),
('Atari 8-bit'),
('MSX'),
('Nintendo Entertainment System (NES)'),
('ZX Spectrum'),
('Atari 5200'),
('Atari 7800'),
('BBC Microcomputer System'),
('Arcade'),
('WiiWare'),
('Philips CD-i'),
('Sharp X68000'),
('Sega Master System'),
('TurboGrafx-16/PC Engine'),
('Super Famicom'),
('Web browser'),
('Tapwave Zodiac'),
('Family Computer Disk System'),
('MSX2'),
('Family Computer'),
('Mobile'),
('Virtual Console (Nintendo)'),
('WonderSwan'),
('Sega 32X'),
('Ouya'),
('Nintendo 3DS'),
('N-Gage'),
('Apple IIGS'),
('BlackBerry OS');
