INSERT INTO `awolski`.`Theme` (`ThemeName`) VALUES 
('Action'),
('Fantasy'),
('Stealth'),
('unknown'),
('Horror'),
('Thriller'),
('Science fiction'),
('Survival'),
('Warfare'),
('Comedy'),
('Sandbox'),
('Open world'),
('Historical'),
('4X (explore, expand, exploit, and exterminate)'),
('Kids'),
('Business'),
('Non-fiction'),
('Drama'),
('Educational');
